"""
Wire protocol types for TopicBlock native component.

AUTO-GENERATED by scripts/gen_schema.py from extension/src/shared/wire.ts.
Do not edit by hand — run `python scripts/gen_schema.py` to regenerate.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

# ---- Shared sub-types ----

@dataclass
class SegmentInput:
    id: str
    body: str
    site: str
    headline: str | None = None
    subtitle: str | None = None
    lang: str | None = None
    extractionHint: Literal["raw_html", "plain_text"] | None = None

@dataclass
class Verdict:
    segmentId: str
    topics: list[dict[str, Any]]
    blocked: bool
    reasons: list[str]
    latencyMs: float
    sentiment: dict[str, Any] | None = None

@dataclass
class ClassifyRequest:
    requestId: str
    segments: list[SegmentInput]
    prefsVersion: int

@dataclass
class ClassifyResponse:
    requestId: str
    verdicts: list[Verdict]
    engineLatencyMs: float

@dataclass
class HealthStatus:
    ok: bool
    version: str
    loadedTopicModel: str
    loadedSentimentModel: str
    device: Literal["cpu", "cuda", "mps"]
    queueDepth: int

@dataclass
class ModelInfo:
    kind: Literal["topic", "sentiment"]
    name: str
    version: str
    backbone: str
    maxSeqLen: int
    defaultThreshold: float
    hwRequirements: dict[str, Any]

@dataclass
class UserPreferences:
    bannedTopics: list[str]
    topicThreshold: float
    sentimentThreshold: float
    sentimentEnabled: bool
    topicModel: str
    sentimentModel: Literal["vader", "distilbert-sst2"]
    action: Literal["hide", "blur", "remove"]
    hoverToReveal: bool
    perSiteOverrides: dict[str, dict[str, Any]] = field(default_factory=dict)

@dataclass
class NativeTelemetryEntry:
    ts: float
    stage: str
    segmentId: str
    latencyMs: float
    source: str


# ---- Wire message envelopes ----

@dataclass
class WireClassify:
    type: Literal["classify"]
    payload: ClassifyRequest

@dataclass
class WireUpdatePrefs:
    type: Literal["update_prefs"]
    payload: UserPreferences

@dataclass
class WireListModels:
    type: Literal["list_models"]

@dataclass
class WireHealth:
    type: Literal["health"]

@dataclass
class WireTelemetryDump:
    type: Literal["telemetry_dump"]

@dataclass
class WireClassifyResult:
    type: Literal["classify_result"]
    payload: ClassifyResponse

@dataclass
class WirePrefsAck:
    type: Literal["prefs_ack"]
    payload: dict[str, Any]

@dataclass
class WireModelsList:
    type: Literal["models_list"]
    payload: list[ModelInfo]

@dataclass
class WireHealthResult:
    type: Literal["health_result"]
    payload: HealthStatus

@dataclass
class WireError:
    type: Literal["error"]
    payload: dict[str, Any]

@dataclass
class WireTelemetryDumpResult:
    type: Literal["telemetry_dump_result"]
    payload: dict[str, Any]

